# Generated by Django 4.1.1 on 2022-09-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_goal_remove_agegroup_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessuser',
            name='description',
        ),
    ]
