# Generated by Django 4.1.1 on 2022-09-17 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_fitnessuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='purpose',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
