# Generated by Django 4.1.1 on 2022-09-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_remove_workout_template_goal_and_more'),
        ('users', '0005_userlist_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuser',
            name='template',
            field=models.ManyToManyField(to='workout.workout_template'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='exercise_frequency',
            field=models.IntegerField(choices=[(0, '1x-2x a week.'), (1, '3x-4x a week.'), (2, '5x-6x a week.')], default=1),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='goal',
            field=models.IntegerField(choices=[(0, 'Weight Loss'), (1, 'Weight gain'), (3, 'Weight Maintenance')], default=1),
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
