# Generated by Django 4.1.1 on 2022-09-22 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_remove_singleworkout_template_week_and_more'),
        ('users', '0006_fitnessuser_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessuser',
            name='template',
        ),
        migrations.AddField(
            model_name='fitnessuser',
            name='template_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workout_template'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='goal',
            field=models.IntegerField(choices=[(0, 'Weight Loss'), (1, 'Weight gain'), (2, 'Weight Maintenance')], default=1),
        ),
    ]
