# Generated by Django 4.1.1 on 2022-09-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_userlist_fitnessuser_completed_workouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='email',
            field=models.EmailField(max_length=60),
        ),
    ]
