# Generated by Django 4.1.1 on 2022-09-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('exercise_1', models.TextField()),
                ('description_1', models.TextField()),
                ('exercise_2', models.TextField()),
                ('description_2', models.TextField()),
                ('exercise_3', models.TextField()),
                ('description_3', models.TextField()),
                ('exercise_4', models.TextField()),
                ('description_4', models.TextField()),
                ('exercise_5', models.TextField()),
                ('description_5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
