# Generated by Django 4.1.1 on 2022-09-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='SingleWorkout',
        ),
    ]
