# Generated by Django 4.1.1 on 2022-09-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_week_name_workout_template_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout_template',
            name='goal',
        ),
        migrations.AddField(
            model_name='singleworkout',
            name='completed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singleworkout',
            name='template_week',
            field=models.ManyToManyField(to='workout.week'),
        ),
        migrations.AddField(
            model_name='week',
            name='goal',
            field=models.IntegerField(choices=[(0, 'Weight Loss'), (1, 'Weight gain'), (3, 'Weight Maintenance')], default=1),
        ),
        migrations.AddField(
            model_name='week',
            name='template',
            field=models.ManyToManyField(to='workout.workout_template'),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='frequency',
            field=models.IntegerField(choices=[(0, '1x-2x a week.'), (1, '3x-4x a week.'), (2, '5x-6x a week.')], default=1),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='purpose',
            field=models.IntegerField(choices=[(0, 'Weight Loss'), (1, 'Weight gain'), (3, 'Weight Maintenance')], default=3),
        ),
    ]
