# Generated by Django 4.1.1 on 2022-09-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_remove_workout_template_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleworkout',
            name='template_week',
        ),
        migrations.RemoveField(
            model_name='week',
            name='template',
        ),
        migrations.RemoveField(
            model_name='workout_template',
            name='purpose',
        ),
        migrations.AddField(
            model_name='week',
            name='exercise_list',
            field=models.ManyToManyField(to='workout.singleworkout'),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='goal',
            field=models.IntegerField(choices=[(0, 'Weight Loss'), (1, 'Weight gain'), (2, 'Weight Maintenance')], default=2),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='weeks',
            field=models.ManyToManyField(to='workout.week'),
        ),
        migrations.AlterField(
            model_name='week',
            name='goal',
            field=models.IntegerField(choices=[(0, 'Weight Loss'), (1, 'Weight gain'), (2, 'Weight Maintenance')], default=1),
        ),
    ]
