# Generated by Django 4.1.1 on 2022-09-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_singleworkout_display_name_singleworkout_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='completed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='completed_status',
            field=models.BooleanField(default=False),
        ),
    ]
