# Generated by Django 4.1.1 on 2022-09-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_week_completed_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleworkout',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
