# Generated by Django 4.1.1 on 2022-09-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_alter_week_goal_alter_workout_template_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='frequency',
            field=models.IntegerField(choices=[(0, '1x-2x a week.'), (1, '3x-4x a week.'), (2, '5x-6x a week.')], default=1),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='description',
            field=models.TextField(default='Test Description'),
        ),
    ]
